### PR TITLE
feat: isolation policy/isolation profiles

### PR DESCRIPTION
**Pull request by martinkiska**
Hi @mitchos,

At the beginning let me thank you for your work done on this SDK.

We started using Isolation profiles/policies in prod on Zscaler tenant. That configuration is currently not available via this SDK. We want to push everything via YAML and APIs, but this was missing - that was our motivation to create this PR.

Added support for ZPA Isolation configuration via API (profiles and policies). Tests for created functions were also added. Docstring were updated in other methods to show, that they support new policy_type - isolation (reorder,update,delete). All added methods were tested directly with Zscaler API endpoints.

### CODE REVIEW

**Comment by martinkiska** [comment]
Hi @mitchos - I see that you are already working on 1.7.0 dev branch according to latest notifications. Can you let me know if this PR is going to be part of it?

**Comment by mitchos** [comment]
Hi @martinkiska I do apologise, I completely missed this PR. I will review it now and merge it in ASAP.

**Review by mitchos — APPROVED** [review]
Reviewed. No problems here.

**Comment by mitchos** [comment]
Thank you again for this high-quality contribution @martinkiska.

**Comment by martinkiska** [comment]
You are welcome @mitchos. I am glad that this project is moving forward! :) It would be nice to have more contributors in general or direct support from the vendor.

**Pull request merged**
